# Generated by Django 6.0.3 on 2026-05-08 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("purpose", models.CharField(choices=[("register", "Register"), ("login", "Login")], max_length=20)),
                ("otp_hash", models.CharField(max_length=128)),
                ("salt", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_otps", to="accounts.user"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "purpose", "expires_at"], name="accounts_em_user_id_4fb7f4_idx"),
                ],
            },
        ),
    ]

