# Generated by Django 6.0.3 on 2026-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_user_id_1b4bd0_idx',
            old_name='accounts_em_user_id_4fb7f4_idx',
        ),
    ]
